# Video network config
videonet:
    backbone_type: resnet
    relu_type: prelu
    width_mult: 1.0
    pretrain: /root/data1/LZR/CTCNet-main/frcnn_128_512.backbone.pth.tar

audionet:
    # sample_rate: 16000
    # filterbank
    n_filters: 512
    kernel_size: 21
    stride: 10
    # masknet
    n_src: 2
    n_blocks: 8
    an_repeats: 3
    fn_repeats: 13
    mask_act: relu
    act_type: prelu
    norm_type: gLN
    bn_chan: 512
    hid_chan: 512
    # video
    vin_chan: 512
    vout_chan: 512
    vconv_kernel_size: 3
    vn_repeats: 5
    # fusion
    fout_chan: 512
    # video frcnn
    video_config:
        in_chan: 64
        out_chan: 64
        depth: 4
        iter: 3
        shared: False
        norm_type: "BatchNorm1d"
        act_type: "prelu"
        kernel_size: 3
# Training config
training:
    epochs: 100
    batch_size: 2
    num_workers: 8
    half_lr: yes
    early_stop: yes
    divide_lr_by: null
    online_mix: false
# Optim config
optim:
    optimizer: adamw
    lr: 0.001
    weight_decay: 0.1
# Sche config
sche:
    patience: 4
    factor: 0.5
# Data config
data:
    train_dir: /root/data1/LSR/data/tr/
    valid_dir: /root/data1/LSR/data/cv/
    nondefault_nsrc: 2
    sample_rate: 16000
    segment: 2.0
    normalize_audio: false
log:
    path: log/tmp
    pro_name: nichang_avproject
    exp_name: lrs2_64_64_3_adamw_1e-1_blocks16_pretrain
TFGridNet:
        n_srcs: 2
        n_fft: 128
        stride: 64
        window: "hann"
        n_imics: 1
        n_layers: 6
        lstm_hidden_units: 192
        attn_n_head: 4
        attn_approx_qk_dim: 512
        emb_dim: 64
        emb_ks: 4
        emb_hs: 1
        activation: "prelu"
        eps: 1.0e-5
        use_builtin_complex: False
        ref_channel: -1
SP_audionet:
#  audionet_name: SPMamba
#  audionet_config:
#    input_dim: 64
    n_srcs: 2
    n_fft: 512
    stride: 128
    window: hann
    n_imics: 1
    n_layers: 6
    lstm_hidden_units: 256
    attn_n_head: 4
    attn_approx_qk_dim: 512
    emb_dim: 64
    emb_ks: 8
    emb_hs: 1
    activation: prelu
    eps: 1.0e-5
    use_builtin_complex: False
    ref_channel: -1
face :
  pool_type: 'maxpool'
  input_channel: 3
  fc_out: 512
  with_fc: False
  weights: '/root/data1/LZR/VisualVoice-main/facial.pth'